project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    keep-md: true
    page-layout: full
  commonmark: default

website:
  navbar:
    title: "Research Group"
    background: "#374152"
    search: true
    logo: logo.jpg
    left:
      - text: Members
        href: members.qmd
      - text: Publications
        href: publications.qmd
    custom-css: styles.css

metadata-files: [nbdev.yml]